#include <iostream>
#include <string>

using namespace std;

void handleYes() {
    cout << "Yay! You are my Valentine!" << endl;
    cout << "[Insert a happy GIF here]" << endl; // You can't display a GIF in the console, but you can show text or ASCII art
}

void handleNo() {
    cout << "Oh no, that's sad! 😢" << endl;
    cout << "[Insert a sad GIF here]" << endl; // Similar to above, a message is displayed instead
}

int main() {
    string response;

    cout << "Will you be my Valentine? (yes/no): ";
    cin >> response;

    // Convert input to lowercase for easier matching
    for (auto &c : response) {
        c = tolower(c);
    }

    if (response == "yes") {
        handleYes();
    } else if (response == "no") {
        handleNo();
    } else {
        cout << "Sorry, I didn't understand that response. Please type 'yes' or 'no'." << endl;
    }

    return 0;
}
